### ISSUE TITLE
Bug with stroke & corner radius

### ISSUE THREAD

**Issue by blobinabottle** [ludushq/issues#28]
https://l.facebook.com/l.php?u=https%3A%2F%2Fapp.ludus.one%2Fb8b87fe1-881e-44c4-8776-e6ef33566308&h=ATO7Uuy0mQzGPYY3VoqY7jo3muGoy4UIwMvLPgMv-ilWPbfgrFn7N2cMOC5g-OhsjdOs4BegU5w9iE22HECnW2TnQNkSeddxt2pufqCwYJ-iH2mMIek7j-P3tMpOSV46F8Zjk2nYdhw5_LM

**Comment by vinch** [comment]
@blobinabottle Can you reproduce this one?

**Comment by jlvan** [comment]
@blobinabottle what's the bug issue here? I don't see what's wrong in the presentation
