### ISSUE TITLE
Improve upload video

### ISSUE THREAD

**Issue by blobinabottle** [ludushq/issues#36]
You can sometimes experience timeout when uploading video.
Need to add a progress bar + progressive upload.

**Comment by vinch** [comment]
https://app.intercom.io/a/apps/cwotamq8/respond/inbox/1259447/conversations/10560022625

**Comment by jlvan** [comment]
video/gif load times, it looks like streamable.com has fasting load times, compared to youtube/vimeo. So I would download directly from youtube/vimeo and upload to streamable.

**Comment by jlvan** [comment]
@blobinabottle should be fixed, right? the upload bar appears when uploading a video or streamable is meant for something else?
