### ISSUE TITLE
Too long string for smart block

### ISSUE THREAD

**Issue by blobinabottle** [ludushq/issues#4]
https://www.facebook.com/groups/ludusPrivate/permalink/1755453631376624/

For now a little issue (at least for me). When you assign a long string to the name of an Smart Block and you want to use it the ADD and DELETE buttons are out of his window, (see pic to have an idea). I can move left and right with trackpad but not with only mouse. I know is a long name but i like self-explained names. My 2 cents --> put in 2 lines, or reduce font size or limit size of the name field.

**Comment by vinch** [comment]
Fixed.
