### ISSUE TITLE
Improve user experience with ChromeOS

### ISSUE THREAD

**Issue by jlvan** [ludushq/issues#59]
#1 it's not very fluidly as before. like, when I try selecting a text, moving the text box around, unselecting it and others
#2 Couldn't add any Icons (Icons8)
#3 problem to make modifications in existing slides

**Comment by jlvan** [comment]
@blobinabottle should be solve by now, isn't it? Didn't hear any problem anymore related to this bug issue

**Comment by blobinabottle** [comment]
nope nothing changed. nothing has been tested.
