### ISSUE TITLE
improve Video Player

### ISSUE THREAD

**Issue by jlvan** [ludushq/issues#71]
When I view a video from an iPhone on Safari and then from a Windows PC in the latest Internet Explorer and Chrome the sound didn’t work for some reason.

**Comment by jlvan** [comment]
video/gif load times, it looks like streamable.com has fasting load times, compared to youtube/vimeo. So I would download directly from youtube/vimeo and upload to streamable.

**Comment by jlvan** [comment]
@blobinabottle The user will have access to the sound of the video since you mute it now?

**Comment by blobinabottle** [comment]
If autoplay, we can't have sound. But user can set up back via video controls (if he chose to view the controls of the video and it's accessible, ie: not behind a rectangle or something).
