### ISSUE TITLE
black borders appear in video

### ISSUE THREAD

**Issue by jlvan** [ludushq/issues#80]

**Comment by blobinabottle** [comment]
Editor? viewer? which gif? which video?

**Comment by jlvan** [comment]
in the viewer. 
![screen shot 2017-08-30 at 9 36 04 pm 2](https://user-images.githubusercontent.com/28731733/29942634-df4e3dd6-8e96-11e7-9ebf-89760e36bf36.png)

**Comment by melvynhills** [comment]
URL please 😊

**Comment by jlvan** [comment]
Discussion transferred in webapp
