### ISSUE TITLE
Remove the uploading feature when error message appears (uploading limit 20MB)

### ISSUE THREAD

**Issue by thupi** [ludushq/issues#85]
I recently tried to upload a large image. I was promted with af message that said i could not upload that large images. I then tried uplaoding a smaller version. This time i was promted with a message saying i was allready uploading.

The uploading feature gets stuck when trying to upload images that is too big :-)

**Comment by jlvan** [comment]
Hello Thupi,
I just saw your bug report. Is your image in a .png format?

**Comment by thupi** [comment]
I do believe it was a JPG file but not sure. It is one of those though :-)

I will try to figure it out in 15 min if that helps :-)

**Comment by jlvan** [comment]
Ok right, yes we would have liked to test it :) if you can send me the picture to jennifer@ludus.one , it would be even better. Thanks for your feedback!

**Comment by jlvan** [comment]
@thupi Actually we just test it. We saw the uploading issue. Thanks for reporting it :)

**Comment by thupi** [comment]
@jlvan Alright :-)

What, thanks for Ludus ;-) !
